'use client'; // client component because it uses React state for mobile toggles

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { FC, useState } from 'react';
import clsx from 'clsx';

interface NavItem {
  title: string;
  href: string;
}

/**
 * Reads a JSON file generated at build time (see lib/navigation.ts) that
 * contains the navigation hierarchy.
 */
const NavMenu: FC = () => {
  const pathname = usePathname();
  const [isOpen, setIsOpen] = useState(false);

  // This file will be generated by a small script during the build.
  // For now we hard‑code a minimal example; the script will replace it.
  const items: NavItem[] = [
    { title: 'Home', href: '/' },
    { title: 'Papers', href: '/papers' },
    { title: 'Projects', href: '/projects' },
    { title: 'Services', href: '/services' },
    { title: 'About', href: '/about' }
  ];

  // Helper to check if current path matches item (handles trailing slashes)
  const isActive = (itemHref: string) => {
    const normalizedPathname = pathname.endsWith('/') && pathname !== '/' 
      ? pathname.slice(0, -1) 
      : pathname;
    return normalizedPathname === itemHref;
  };

  return (
    <nav
      aria-label="Primary"
      className="bg-lightSmoke"
    >
      <div className="max-w-4xl mx-auto flex items-center justify-between h-16">
        {/* Brand / logo */}
        <Link href="/" className="flex items-center">
          <span className="text-dpmOlive font-serif-primary text-xl">
            Wize Idea
          </span>
        </Link>

        {/* Desktop menu */}
        <ul className="hidden md:flex space-x-6">
          {items.map(item => (
            <li key={item.href}>
              <Link
                href={item.href}
                className={clsx(
                  'font-sans-ui text-striationCharcoal hover:text-burntOchre transition-colors',
                  isActive(item.href) && 'underline underline-offset-4 decoration-dpmOlive'
                )}
              >
                {item.title}
              </Link>
            </li>
          ))}
        </ul>

        {/* Mobile toggle */}
        <button
          aria-controls="mobile-menu"
          aria-expanded={isOpen}
          onClick={() => setIsOpen(!isOpen)}
          className="md:hidden text-striationCharcoal hover:text-burntOchre"
        >
          <span className="sr-only">Open main menu</span>
          {/* Simple hamburger */}
          <svg
            className="h-6 w-6"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            aria-hidden="true"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d={isOpen ? 'M6 18L18 6M6 6l12 12' : 'M4 6h16M4 12h16M4 18h16'}
            />
          </svg>
        </button>
      </div>

      {/* Mobile menu */}
      {isOpen && (
        <ul
          id="mobile-menu"
          className="md:hidden bg-saltWhite border-t border-dpmOlive"
        >
          {items.map(item => (
            <li key={item.href}>
              <Link
                href={item.href}
                className={clsx(
                  'block px-4 py-2 font-sans-ui text-striationCharcoal hover:bg-dpmOlive hover:text-saltWhite',
                  isActive(item.href) && 'bg-dpmOlive text-saltWhite'
                )}
                onClick={() => setIsOpen(false)}
              >
                {item.title}
              </Link>
            </li>
          ))}
        </ul>
      )}
    </nav>
  );
};

export default NavMenu;