'use client'; // client component because it uses React state for mobile toggles

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { FC, useState, useEffect, useRef } from 'react';
import clsx from 'clsx';

interface NavItem {
  title: string;
  href: string;
}

/**
 * Reads a JSON file generated at build time (see lib/navigation.ts) that
 * contains the navigation hierarchy.
 */
const NavMenu: FC = () => {
  const pathname = usePathname();
  const [isOpen, setIsOpen] = useState(false);
  const mobileMenuRef = useRef<HTMLUListElement>(null);
  const toggleButtonRef = useRef<HTMLButtonElement>(null);

  // Close mobile menu on Escape key press
  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isOpen) {
        setIsOpen(false);
        toggleButtonRef.current?.focus();
      }
    };
    
    document.addEventListener('keydown', handleEscape);
    return () => document.removeEventListener('keydown', handleEscape);
  }, [isOpen]);

  // Focus trap for mobile menu
  useEffect(() => {
    if (!isOpen || !mobileMenuRef.current) return;

    const menuElement = mobileMenuRef.current;
    const focusableElements = menuElement.querySelectorAll(
      'a[href], button:not([disabled])'
    );
    const firstElement = focusableElements[0] as HTMLElement;
    const lastElement = focusableElements[focusableElements.length - 1] as HTMLElement;

    const handleTabKey = (e: KeyboardEvent) => {
      if (e.key !== 'Tab') return;

      if (e.shiftKey) {
        if (document.activeElement === firstElement) {
          lastElement?.focus();
          e.preventDefault();
        }
      } else {
        if (document.activeElement === lastElement) {
          firstElement?.focus();
          e.preventDefault();
        }
      }
    };

    menuElement.addEventListener('keydown', handleTabKey as EventListener);
    firstElement?.focus();

    return () => {
      menuElement.removeEventListener('keydown', handleTabKey as EventListener);
    };
  }, [isOpen]);

  // This file will be generated by a small script during the build.
  // For now we hard‑code a minimal example; the script will replace it.
  const items: NavItem[] = [
    { title: 'Home', href: '/' },
    { title: 'Papers', href: '/papers' },
    { title: 'Projects', href: '/projects' },
    { title: 'Services', href: '/services' },
    { title: 'About', href: '/about' }
  ];

  // Helper to check if current path matches item (handles trailing slashes)
  const isActive = (itemHref: string) => {
    const normalizedPathname = pathname.endsWith('/') && pathname !== '/' 
      ? pathname.slice(0, -1) 
      : pathname;
    return normalizedPathname === itemHref;
  };

  return (
    <nav
      role="navigation"
      aria-label="Primary navigation"
      className="bg-lightSmoke"
    >
      <div className="max-w-4xl mx-auto flex items-center justify-between h-16">
        {/* Brand / logo */}
        <Link href="/" className="flex items-center">
          <span className="text-dpmOlive font-serif-primary text-xl">
            Wize Idea
          </span>
        </Link>

        {/* Desktop menu */}
        <ul className="hidden md:flex space-x-6">
          {items.map(item => (
            <li key={item.href}>
              <Link
                href={item.href}
                className={clsx(
                  'font-sans-ui text-striationCharcoal hover:text-burntOchre transition-colors',
                  isActive(item.href) && 'font-semibold'
                )}
              >
                {item.title}
              </Link>
            </li>
          ))}
        </ul>

        {/* Mobile toggle */}
        <button
          ref={toggleButtonRef}
          aria-controls="mobile-menu"
          aria-expanded={isOpen}
          onClick={() => setIsOpen(!isOpen)}
          className="md:hidden text-striationCharcoal hover:text-burntOchre"
        >
          <span className="sr-only">Open main menu</span>
          {/* Simple hamburger */}
          <svg
            className="h-6 w-6"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            aria-hidden="true"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d={isOpen ? 'M6 18L18 6M6 6l12 12' : 'M4 6h16M4 12h16M4 18h16'}
            />
          </svg>
        </button>
      </div>

      {/* Mobile menu */}
      {isOpen && (
        <ul
          ref={mobileMenuRef}
          id="mobile-menu"
          className="md:hidden bg-saltWhite border-t border-dpmOlive"
        >
          {items.map(item => (
            <li key={item.href}>
              <Link
                href={item.href}
                className={clsx(
                  'block px-4 py-3 font-sans-ui text-striationCharcoal hover:bg-lightSmoke min-h-[44px]',
                  isActive(item.href) && 'bg-lightSmoke font-semibold'
                )}
                onClick={() => setIsOpen(false)}
              >
                {item.title}
              </Link>
            </li>
          ))}
        </ul>
      )}
    </nav>
  );
};

export default NavMenu;